# Простой рабочий процесс для деплоя статического контента на GitHub Pages
name: Развёртывание статического контента на GitHub Pages

on:
  # Запускается при пушах в основную ветку
  push:
    branches: ['main']

  # Позволяет запускать workflow вручную из вкладки Actions
  workflow_dispatch:

# Устанавливает права GITHUB_TOKEN для деплоя на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Разрешает только один одновременный деплой
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Один джоб на деплой, так как мы просто развёртываем
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Установить Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Установить зависимости
        run: npm install
      - name: Сборка
        run: npm run build

      - name: Запустить проект (npm start)
        run: |
          npm start &
          sleep 10
          curl -I http://localhost:3000 || true

      - name: Настроить GitHub Pages
        uses: actions/configure-pages@v3
      - name: Загрузить артефакт
        uses: actions/upload-pages-artifact@v3
        with:
          # Загружаем dist директорию
          path: './dist'
      - name: Деплой на GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
